// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Stand_by
void ui_Stand_by_screen_init(void);
void ui_event_Stand_by(lv_event_t * e);
lv_obj_t * ui_Stand_by;
lv_obj_t * ui_Image2;
// CUSTOM VARIABLES


// SCREEN: ui_Clock
void ui_Clock_screen_init(void);
void ui_event_Clock(lv_event_t * e);
lv_obj_t * ui_Clock;
lv_obj_t * ui_Image5;
// CUSTOM VARIABLES


// SCREEN: ui_SD_Card
void ui_SD_Card_screen_init(void);
void ui_event_SD_Card(lv_event_t * e);
lv_obj_t * ui_SD_Card;
lv_obj_t * ui_Image17;
// CUSTOM VARIABLES


// SCREEN: ui_Serial

// CUSTOM VARIABLES


// SCREEN: ui_Control_Center
void ui_Control_Center_screen_init(void);
void ui_event_Control_Center(lv_event_t * e);
lv_obj_t * ui_Control_Center;
lv_obj_t * ui_Image25;
void ui_event_power_off(lv_event_t * e);
lv_obj_t * ui_power_off;
// CUSTOM VARIABLES


// SCREEN: ui_Apps_Menu
void ui_Apps_Menu_screen_init(void);
lv_obj_t * ui_Apps_Menu;
lv_obj_t * ui_Image26;
lv_obj_t * ui_homebutton;
lv_obj_t * ui_Container2;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_battery_[1] = {&ui_img_battery_3_png};
const lv_img_dsc_t * ui_imgset_micro_sd_card_[1] = {&ui_img_micro_sd_card_4_png};
const lv_img_dsc_t * ui_imgset_rectangle_[1] = {&ui_img_rectangle_12_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Stand_by(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Clock_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Control_Center, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Control_Center_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SD_Card, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SD_Card_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Apps_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Apps_Menu_screen_init);
    }
}

void ui_event_Clock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Stand_by, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Stand_by_screen_init);
    }
}

void ui_event_SD_Card(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Stand_by, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Stand_by_screen_init);
    }
}

// void ui_event_Serial(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);

//     if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
//         lv_indev_wait_release(lv_indev_get_act());
//         _ui_screen_change(&ui_Control_Center, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Control_Center_screen_init);
//     }
// }

void ui_event_Control_Center(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Stand_by, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Stand_by_screen_init);
    }
}

void ui_event_power_off(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        power_off(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Stand_by_screen_init();
    ui_Clock_screen_init();
    ui_SD_Card_screen_init();
    ui_Control_Center_screen_init();
    ui_Apps_Menu_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Stand_by);
}
