// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Stand_by
void ui_Stand_by_screen_init(void);
void ui_event_Stand_by(lv_event_t * e);
extern lv_obj_t * ui_Stand_by;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

// SCREEN: ui_Clock
void ui_Clock_screen_init(void);
void ui_event_Clock(lv_event_t * e);
extern lv_obj_t * ui_Clock;
extern lv_obj_t * ui_Image5;
// CUSTOM VARIABLES

// SCREEN: ui_SD_Card
void ui_SD_Card_screen_init(void);
void ui_event_SD_Card(lv_event_t * e);
extern lv_obj_t * ui_SD_Card;
extern lv_obj_t * ui_Image17;
// CUSTOM VARIABLES

// SCREEN: ui_Control_Center
void ui_Control_Center_screen_init(void);
void ui_event_Control_Center(lv_event_t * e);
extern lv_obj_t * ui_Control_Center;
extern lv_obj_t * ui_Image25;
void ui_event_power_off(lv_event_t * e);
extern lv_obj_t * ui_power_off;
// CUSTOM VARIABLES

// SCREEN: ui_Apps_Menu
void ui_Apps_Menu_screen_init(void);
extern lv_obj_t * ui_Apps_Menu;
extern lv_obj_t * ui_Image26;
extern lv_obj_t * ui_homebutton;
extern lv_obj_t * ui_Container2;

LV_IMG_DECLARE(ui_img_dino_png);
LV_IMG_DECLARE(ui_img_vscode_png);
LV_IMG_DECLARE(ui_img_led_png);
LV_IMG_DECLARE(ui_img_mac_png);
LV_IMG_DECLARE(ui_img_wifitv_png);
LV_IMG_DECLARE(ui_img_air_mouse_png);    // assets/air mouse.png
LV_IMG_DECLARE(ui_img_badusb_png);    // assets/BadUSB.png
LV_IMG_DECLARE(ui_img_machine_learning_png);    // assets/Machine Learning.png
LV_IMG_DECLARE(ui_img_spam_apple_png);    // assets/Spam Apple.png
LV_IMG_DECLARE(ui_img_webserial_png);    // assets/webserial.png
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_standby_png);    // assets/Standby.png
LV_IMG_DECLARE(ui_img_dynamic_clock_png);    // assets/Dynamic Clock.png
LV_IMG_DECLARE(ui_img_file_png);    // assets/file.png
LV_IMG_DECLARE(ui_img_control_center_png);    // assets/Control Center.png
LV_IMG_DECLARE(ui_img_app_bg_png);    // assets/app_BG.png
LV_IMG_DECLARE(ui_img_sd_card_png);    // assets/SD Card.png
LV_IMG_DECLARE(ui_img_battery_3_png);    // assets/battery 3.png
LV_IMG_DECLARE(ui_img_home_png); 
LV_IMG_DECLARE(ui_img_micro_sd_card_4_png);    // LV_IMG_DECLARE(ui_img_home_png); assets/Micro SD Card 4.png
LV_IMG_DECLARE(ui_img_rectangle_12_png);    // assets/Rectangle 12.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
