// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <stdio.h>


// 定义全局变量
int selected_app_index = -1;  // 初始值为 -1，表示没有选择任何 app
static lv_obj_t * index_label = NULL;

static void scroll_event_cb(lv_event_t * e)
{
    lv_obj_t * cont = lv_event_get_target(e);

    lv_area_t cont_a;
    lv_obj_get_coords(cont, &cont_a);
    lv_coord_t cont_y_center = cont_a.y1 + lv_area_get_height(&cont_a) / 2;

    lv_coord_t r = lv_obj_get_height(cont) * 7 / 10;
    uint32_t i;
    uint32_t child_cnt = lv_obj_get_child_cnt(cont);
    for(i = 0; i < child_cnt; i++) {
        lv_obj_t * child = lv_obj_get_child(cont, i);
        lv_area_t child_a;
        lv_obj_get_coords(child, &child_a);

        lv_coord_t child_y_center = child_a.y1 + lv_area_get_height(&child_a) / 2;

        lv_coord_t diff_y = child_y_center - cont_y_center;
        diff_y = LV_ABS(diff_y);

        /*Get the x of diff_y on a circle.*/
        lv_coord_t x;
        /*If diff_y is out of the circle use the last point of the circle (the radius)*/
        if(diff_y >= r) {
            x = r;
        }
        else {
            /*Use Pythagoras theorem to get x from radius and y*/
            uint32_t x_sqr = r * r - diff_y * diff_y;
            lv_sqrt_res_t res;
            lv_sqrt(x_sqr, &res, 0x8000);   /*Use lvgl's built in sqrt root function*/
            x = r - res.i;
        }

        /*Translate the item by the calculated X coordinate*/
        lv_obj_set_style_translate_x(child, x, 0);

        /*Use some opacity with larger translations*/
        lv_opa_t opa = lv_map(x, 0, r, LV_OPA_TRANSP, LV_OPA_COVER);
        lv_obj_set_style_opa(child, LV_OPA_COVER - opa, 0);
    }
}

static void button_event_cb(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_target(e);    // 获取触发事件的目标对象
    lv_event_code_t code = lv_event_get_code(e);  // 获取事件的代码（事件类型）

    // 如果是按钮点击事件
    if (code == LV_EVENT_CLICKED) {
    selected_app_index = lv_obj_get_index(obj);

    // 如果已有标签，先删除
    if (index_label) {
        lv_obj_del(index_label);
        index_label = NULL;
    }

    // 创建新的标签
    index_label = lv_label_create(lv_scr_act());
    char buf[64];
    snprintf(buf, sizeof(buf), "App Index: %d", selected_app_index);
    lv_label_set_text(index_label, buf);
    lv_obj_align(index_label, LV_ALIGN_BOTTOM_MID, 0, -10);
    lv_obj_set_style_text_color(index_label, lv_color_white(), LV_PART_MAIN);
}

}

void ui_Apps_Menu_screen_init(void)
{
    ui_Apps_Menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Apps_Menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image26 = lv_img_create(ui_Apps_Menu);
    lv_img_set_src(ui_Image26, &ui_img_app_bg_png);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_homebutton = ui_homebutton_create(ui_Apps_Menu);
    lv_obj_set_x(ui_homebutton, 135);
    lv_obj_set_y(ui_homebutton, -95);
    lv_obj_set_style_radius(ui_homebutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_homebutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homebutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_homebutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_homebutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

/* Create a container with size 260x240 */
    // 确保 ui_Apps_Menu 已经加载为当前屏幕
    lv_scr_load(ui_Apps_Menu);

    // 创建容器时，直接将 ui_Apps_Menu 作为父对象
    lv_obj_t * cont = lv_obj_create(ui_Apps_Menu);
    lv_obj_set_size(cont, 260, 240);
    lv_obj_set_pos(cont, 0, 0);
    lv_obj_set_flex_flow(cont, LV_FLEX_FLOW_COLUMN);
    // 设置容器背景和边框透明
    lv_obj_set_style_bg_opa(cont, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_border_opa(cont, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_add_event_cb(cont, scroll_event_cb, LV_EVENT_SCROLL, NULL);  // 添加滚动事件

    lv_obj_set_scroll_dir(cont, LV_DIR_VER);  // 垂直滚动
    lv_obj_set_scroll_snap_y(cont, LV_SCROLL_SNAP_CENTER);  // 滚动到中心时自动对齐
    lv_obj_set_scrollbar_mode(cont, LV_SCROLLBAR_MODE_OFF);  // 禁用滚动条

    /* 图标和名称列表 */
    const char * app_names[] = { "led", "Dino","computer", "spam iphone", "wifi killer", "badusb", "wifi TV", "webserial" ,"air mouse"};
    const lv_img_dsc_t * app_icons[] = { &ui_img_led_png, &ui_img_dino_png,&ui_img_mac_png, &ui_img_spam_apple_png, &ui_img_vscode_png,
                                         &ui_img_badusb_png,&ui_img_wifitv_png,&ui_img_webserial_png,&ui_img_air_mouse_png};

    /* Place App on the desktop panel */
    for (int i = 0; i < sizeof(app_names) / sizeof(app_names[0]); i++) {
        /* Apps' Icon (button) */
        lv_obj_t * app_btn = lv_btn_create(cont);
        lv_obj_set_width(app_btn, lv_pct(100));
        lv_obj_set_height(app_btn, 85); // 设置按钮高度为85像素
        // 设置按钮背景为透明
        lv_obj_set_style_bg_opa(app_btn, LV_OPA_TRANSP, LV_PART_MAIN);
        // 移除按钮边缘和阴影
        lv_obj_set_style_shadow_width(app_btn, 0, LV_PART_MAIN);
        // 使用flex布局，将图标和文字从左到右排列
        lv_obj_set_flex_flow(app_btn, LV_FLEX_FLOW_ROW);
        lv_obj_set_flex_align(app_btn, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);


        /* Set the background image directly on the button */
        lv_obj_t * img = lv_img_create(app_btn);  // 创建图像并将其添加到按钮上
        lv_img_set_src(img, app_icons[i]);  // 设置图像源

        /* Apps' name */
        lv_obj_t * label = lv_label_create(app_btn);
        lv_label_set_text(label, app_names[i]);  // 设置按钮名称
        lv_obj_set_size(label, LV_SIZE_CONTENT, LV_SIZE_CONTENT); // 让label自适应内容
        lv_obj_set_style_text_color(label, lv_color_white(), LV_PART_MAIN);  // 设定字体颜色
        lv_obj_set_style_text_opa(label, LV_OPA_COVER, LV_PART_MAIN); // 设定字体完全不透明
        lv_obj_set_style_text_font(label, &ui_font_Font1, LV_PART_MAIN);  // 使用默认字体
        lv_obj_set_style_pad_left(label, 10, LV_PART_MAIN);  // 文字和图标之间增加间距

        // 确保 label 总是可见
        lv_obj_set_style_opa(label, LV_OPA_COVER, LV_PART_MAIN);

        /* Setup event call back */
        lv_obj_add_event_cb(app_btn, button_event_cb, LV_EVENT_CLICKED, NULL);
    }

    /*Update the position of the elements manually for the first time*/
    lv_event_send(cont, LV_EVENT_SCROLL, NULL);//手动触发滚动事件

    /*确保第二个元素位于中心*/
    lv_obj_scroll_to_view(lv_obj_get_child(cont, 1), LV_ANIM_OFF);

}
