// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Control_Center_screen_init(void)
{
    ui_Control_Center = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Control_Center, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image25 = lv_img_create(ui_Control_Center);
    lv_img_set_src(ui_Image25, &ui_img_control_center_png);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_power_off = lv_obj_create(ui_Control_Center);
    lv_obj_set_width(ui_power_off, 40);
    lv_obj_set_height(ui_power_off, 40);
    lv_obj_set_x(ui_power_off, -50);
    lv_obj_set_y(ui_power_off, 80);
    lv_obj_set_align(ui_power_off, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_power_off, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_power_off, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_power_off, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_power_off, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_power_off, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_power_off, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_power_off, ui_event_power_off, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Control_Center, ui_event_Control_Center, LV_EVENT_ALL, NULL);

}
