// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


void ui_event_comp_homebutton_homebutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_homebutton = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Stand_by, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Stand_by_screen_init);
    }
}

// COMPONENT homebutton

lv_obj_t * ui_homebutton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_homebutton;
    cui_homebutton = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_homebutton, 40);
    lv_obj_set_height(cui_homebutton, 40);
    lv_obj_set_x(cui_homebutton, 135);
    lv_obj_set_y(cui_homebutton, -95);
    lv_obj_set_align(cui_homebutton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_homebutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Image29;
    cui_Image29 = lv_img_create(cui_homebutton);
    lv_img_set_src(cui_Image29, &ui_img_home_png);
    lv_obj_set_width(cui_Image29, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(cui_Image29, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(cui_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image29, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_HOMEBUTTON_NUM);
    children[UI_COMP_HOMEBUTTON_HOMEBUTTON] = cui_homebutton;
    children[UI_COMP_HOMEBUTTON_IMAGE29] = cui_Image29;
    lv_obj_add_event_cb(cui_homebutton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_homebutton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_homebutton, ui_event_comp_homebutton_homebutton, LV_EVENT_ALL, children);
    ui_comp_homebutton_create_hook(cui_homebutton);
    return cui_homebutton;
}

