// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_HOMEBUTTON_H
#define _UI_COMP_HOMEBUTTON_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT homebutton
#define UI_COMP_HOMEBUTTON_HOMEBUTTON 0
#define UI_COMP_HOMEBUTTON_IMAGE29 1
#define _UI_COMP_HOMEBUTTON_NUM 2
lv_obj_t * ui_homebutton_create(lv_obj_t * comp_parent);
void ui_event_comp_homebutton_homebutton(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
