// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "Arduino.h"
void power_off(lv_event_t * e)
{
	// Your code here
	pinMode(11,OUTPUT);
	digitalWrite(11,LOW); // 执行关机操作
}
