// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_SD_Card_screen_init(void)
{
    ui_SD_Card = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SD_Card, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_img_create(ui_SD_Card);
    lv_img_set_src(ui_Image17, &ui_img_file_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_SD_Card, ui_event_SD_Card, LV_EVENT_ALL, NULL);

}
